# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
#  - windows % The language 'julia' is currently unsupported on the Windows Build Environment.
julia:
#  - 1.1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
codecov: true
coveralls: true
before_script:
  - julia -e 'import Pkg; Pkg.add("Test")'